### ISSUE TITLE
When using `cache_path` option I get: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by NielsKSchjoedt** [rails/actionpack-action_caching#40]
![skaermbillede 2016-12-20 kl 10 54 30](https://cloud.githubusercontent.com/assets/570755/21346010/cbcefdd4-c6a2-11e6-969f-333521289558.png)

My controller:

```ruby
  caches_action :front_page, cache_path: -> do
    request.original_url
  end

  layout 'basic_page'

  def front_page
    @featured_article_search = CarSearch.new({
          max_price:        25000
    })
    @brands = PopularBrands::Repository.brands

    render layout: 'front_page'
  end
```

Stacktrace:
```
app/controllers/au_controller.rb:42:in `block in <class:auController>'
/Users/NK/.rvm/gems/ruby-2.3.0@au_rails42/bundler/gems/actionpack-action_caching-a5f48da050cd/lib/action_controller/caching/actions.rb:187:in `instance_exec'
/Users/NK/.rvm/gems/ruby-2.3.0@au_rails42/bundler/gems/actionpack-action_caching-a5f48da050cd/lib/action_controller/caching/actions.rb:187:in `expand_option'
/Users/NK/.rvm/gems/ruby-2.3.0@au_rails42/bundler/gems/actionpack-action_caching-a5f48da050cd/lib/action_controller/caching/actions.rb:156:in `around'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:455:in `public_send'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:455:in `block in make_lambda'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:291:in `block in halting_and_conditional'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
route_translator (4.4.1) lib/route_translator/extensions/action_controller.rb:27:in `set_locale_from_url'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:312:in `block in halting'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
apipie-rails (0.3.7) lib/apipie/static_dispatcher.rb:65:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.1) lib/omniauth/builder.rb:63:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
apipie-rails (0.3.7) lib/apipie/extractor/recorder.rb:132:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
apartment (1.2.0) lib/apartment/reloader.rb:18:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
request_store_rails (1.0.1) lib/request_store_rails/middleware.rb:17:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
honeybadger (2.6.1) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (2.6.1) lib/honeybadger/config.rb:200:in `with_request'
honeybadger (2.6.1) lib/honeybadger/rack/error_notifier.rb:30:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
honeybadger (2.6.1) lib/honeybadger/rack/user_feedback.rb:28:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
honeybadger (2.6.1) lib/honeybadger/rack/user_informer.rb:18:in `call'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
railties (4.2.7.1) lib/rails/application.rb:165:in `call'
railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
newrelic_rpm (3.17.1.326) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:155:in `handle'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:109:in `rescue in block (2 levels) in start'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:106:in `block (2 levels) in start'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `each'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `start'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
/Users/NK/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'
```

Gemfile.lock:
```
GIT
  remote: https://github.com/rails/actionpack-action_caching
  revision: a5f48da050cd06624835748c29ddefee8ba03010
  specs:
    actionpack-action_caching (1.1.1)
      actionpack (>= 4.0.0, < 6)
```
Rails 4.2.7

**Comment by pixeltrix** [comment]
This is a subtle difference between `Proc.new` and `->` - the latter has it's arity enforced whereas the former doesn't. We can probably work around it by checking the arity of the proc before calling it [here][1].

[1]: https://github.com/rails/actionpack-action_caching/blob/a5f48da050cd06624835748c29ddefee8ba03010/lib/action_controller/caching/actions.rb#L185-L193
